name: Building ICSC for Linux

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Set ICSC_HOME
        run: echo "ICSC_HOME=$HOME/icsc_home" >> $GITHUB_ENV

      - name: Clone ICSC
        run: git clone https://github.com/intel/systemc-compiler $ICSC_HOME/icsc

      - name: Cache LLVM + Protobuf
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.ICSC_HOME }}/lib
            ${{ env.ICSC_HOME }}/lib64
            ${{ env.ICSC_HOME }}/include
            ${{ env.ICSC_HOME }}/bin
          key: icsc-deps-ubuntu22-${{ hashFiles('**/install.sh') }}

      - name: Run install.sh
        run: |
          cd $ICSC_HOME
          icsc/install.sh

      - name: Bundle ICSC_HOME as tarball
        run: |
          cd $HOME
          tar -czf icsc_bundle.tar.gz icsc_home/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: icsc-ubuntu22-bundle
          path: ~/icsc_bundle.tar.gz
          retention-days: 30
